version: "3.9"

services:
  frontend:
    platform: linux/amd64
    build:
      context: ../client
      dockerfile: ../docker/Dockerfile.client   # 👈 Шлях відносно docker-compose.yml
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build:
      # context: ../server
      dockerfile: ./Dockerfile.server   # 👈 також відносно docker-compose.yml
    ports:
      - "8000:8000"
    volumes:
      - ../server:/app
    command: uvicorn main:app --host 0.0.0.0 --reload
